"""add field to answers table

Revision ID: 4a15e4b06483
Revises: 6f85c95bf200
Create Date: 2026-06-08 19:14:40.776888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a15e4b06483'
down_revision: Union[str, Sequence[str], None] = '6f85c95bf200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('judge_explaination', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'judge_explaination')
    # ### end Alembic commands ###
