"""rename field in answers table

Revision ID: 6f85c95bf200
Revises: 88fba8dc22c2
Create Date: 2026-06-08 19:10:33.744838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f85c95bf200'
down_revision: Union[str, Sequence[str], None] = '88fba8dc22c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('llm_answer', sa.String(), nullable=False))
    op.drop_column('answers', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'llm_answer')
    # ### end Alembic commands ###
