"""add new fields to tasks

Revision ID: 829328924762
Revises: 
Create Date: 2026-06-05 23:43:14.089790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829328924762'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('published_date', sa.Date(), nullable=False))
    op.add_column('tasks', sa.Column('source_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'source_url')
    op.drop_column('tasks', 'published_date')
    # ### end Alembic commands ###
