"""rename field in llms

Revision ID: 9668095412e0
Revises: 9a5cbf0ef87b
Create Date: 2026-06-07 01:45:35.814105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9668095412e0'
down_revision: Union[str, Sequence[str], None] = '9a5cbf0ef87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llms', sa.Column('llm_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('llms_model_name_key'), 'llms', type_='unique')
    op.create_unique_constraint(None, 'llms', ['llm_name'])
    op.drop_column('llms', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llms', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'llms', type_='unique')
    op.create_unique_constraint(op.f('llms_model_name_key'), 'llms', ['model_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('llms', 'llm_name')
    # ### end Alembic commands ###
