"""rename field in llms

Revision ID: 9a5cbf0ef87b
Revises: 829328924762
Create Date: 2026-06-06 23:42:35.345512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5cbf0ef87b'
down_revision: Union[str, Sequence[str], None] = '829328924762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llms', sa.Column('model_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('llms_name_key'), 'llms', type_='unique')
    op.create_unique_constraint(None, 'llms', ['model_name'])
    op.drop_column('llms', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llms', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'llms', type_='unique')
    op.create_unique_constraint(op.f('llms_name_key'), 'llms', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('llms', 'model_name')
    # ### end Alembic commands ###
